name: ai_language
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  intl_phone_number_input: ^0.7.2
  country_pickers: ^2.0.0
  pinput: ^2.2.21
  go_router: ^6.2.0
  animated_bottom_navigation_bar: ^1.1.0+1
  audio_video_progress_bar: ^1.0.0
  holding_gesture: ^1.1.0
  avatar_glow: ^2.0.2
  flutter_native_splash: ^2.2.9

  # Platform features
  file_picker: ^5.2.5
  image_picker: ^1.0.0

  # DI
  injectable: ^2.1.0
  get_it: ^7.2.0

  #  State management
  redux: ^5.0.0
  redux_simple:
    git: git@github.com:Nhinlee/redux_simple.git
  flutter_redux: ^0.10.0
  redux_logging: ^0.5.0

  # Built value
  built_value: ^8.4.3
  built_collection: ^5.1.1

  # Network
  dio: ^5.0.1

  # Utils
  uuid: ^3.0.7
  logging: ^1.0.2

dev_dependencies:
  # linter
  flutter_lints: ^2.0.0

  # DI
  injectable_generator: ^2.1.4

  # Built value
  built_value_generator: ^8.4.2
  build_runner: any

  # Test
  flutter_test:
    sdk: flutter
  test: ^1.21.4


# gen assets
flutter_gen:
  output: lib/res/flutter_gen # Optional (default: lib/gen/)
  assets:
    enabled: true

    # Set to true if you want this package to be a package dependency
    # See: https://flutter.dev/docs/development/ui/assets-and-images#from-packages
    package_parameter_enabled: true

    style: dot-delimiter

  fonts:
    enabled: true

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
